import React from 'react'
import Footer from '../components/Footer'

const TermsAndCondition = () => {
	return (
		<>
			<div className='w-screen absolute top-32 bg-gray-700'>
				<div className='pt-10'>
					<h1 className='px-5 lg:block lg:px-44 text-xl lg:text-4xl pb-10 accent-text-color lg:text-left text-center'>TERMS AND CONDITIONS</h1>
					<div className='bg-gray-900 py-9 px-5 lg:px-36'>
						<div className='w-full py-6 px-3 text-center text-white flex items-center flex-col'>
							<h1 className='text-2xl lg:text-3xl'>PRIVACY AND SECURITY POLICIES</h1>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway mb-6 text-gray-300 mt-4'>We are committed to protecting and respecting your privacy. This clause 1 sets out the basis on which any personal data we collect from you, or which you provide to us, will be processed by us. By visiting our website you are accepting and consenting to the practices described in this clause 1.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway mb-6 text-gray-300'>1.1 We may collect and process the following data about you: (a) You may give us information about you by filling in forms on our website or by corresponding with us by phone, email or otherwise. This includes information you provide when you register to use our site, subscribe to our service, search for a product, place an order on our site, participate in discussion boards or other social media functions on our site, enter a competition, promotion or survey, and when you report a problem with our site. The information you give us may include your name, address, email address and phone number, financial and credit card information.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway mb-6 text-gray-300'>1.2 We use information held about you in the following ways: (a) Information you give to us. We will use this information: (i) to carry out our obligations arising from any contracts entered into between you and us and to provide you with the information, products and services that you request from us; (ii) to provide you with information about other goods and services we offer that are similar to those that you have already purchased or enquired about; (iii) to provide you with information about goods or services we feel may interest you in pursuant of our legitimate business interests. If you are an existing customer, we will only contact you by electronic means (email or SMS) with information about goods and services similar to those which were the subject of a previous sale or negotiations of a sale to you. If you are a new customer we will contact you by electronic means only if you have consented to this. If you do not want us to use your data in this way, please let us know. (iv) to notify you about changes to our service; (v) to ensure that content from our website is presented in the most effective manner for you and for your computer.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway mb-6 text-gray-300'>1.3 Information we collect about you. We will use this information: (a) to administer our website and for internal operations, including troubleshooting, data analysis, testing, research, statistical and survey purposes; (b) to improve our website to ensure that content is presented in the most effective manner for you and for your computer; (c) to allow you to participate in interactive features of our service, when you choose to do so; (d) as part of our efforts to keep our site safe and secure; (e) to measure or understand the effectiveness of advertising we serve to you and others, and to deliver relevant advertising to you; (f) to make suggestions and recommendations to you and other users of our website about goods or services that may interest you or them.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway mb-6 text-gray-300'>1.4 Disclosure of your information: (a) We may disclose your personal information to our professional advisors or if we are under a duty to do so in order to comply with any legal obligation.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway mb-6 text-gray-300'>1.5 Where we store your personal data (a) the data that we collect from you may be transferred to, and stored at, a destination outside the European Economic Area (“EEA”), where your data is being transferred outside of the EEA we will endeavour to protect your data with appropriate safeguards such as the EU-U.S. Privacy Shield, European Commission decision 2002/2/EC, Binding Corporate Rules or other appropriate safeguards. It may also be processed by staff operating outside the EEA who work for us or for one of our suppliers. Such staff maybe engaged in, among other things, the fulfilment of your order, the processing of your payment details and the provision of support services. By submitting your personal data, you agree to this transfer, storing or processing. We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this privacy policy. (b) Where we have given you (or where you have chosen) a password which enables you to access certain parts of our site, you are responsible for keeping this password confidential. We ask you not to share a password with anyone. (c) Unfortunately, the transmission of information via the internet is not completely secure. Although we will do our best to protect your personal data, we cannot guarantee the security of your data transmitted to our site; any transmission is at your own risk. Once we have received your information, we will use strict procedures and security features to try to prevent unauthorised access.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway mb-6 text-gray-300'>1.6 Your rights (a) You have the right to ask us not to process your personal data for marketing purposes. We will usually inform you (before collecting your data) if we intend to use your data for such purposes or if we intend to disclose your information to any third party for such purposes. You can exercise your right to prevent such processing by checking certain boxes on the forms we use to collect your data. You can also exercise the right at any time by contacting our Customer Services team. (b) Our website may, from time to time, contain links to and from the websites of our partner networks, advertisers and affiliates. If you follow a link to any of these websites, please note that these websites have their own privacy policies and that we do not accept any responsibility or liability for these policies. Please check these policies before you submit any personal data to these websites.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway mb-1 text-gray-300'>1.7 Access to information (a) European Union's General Data Protection Regulation (GDPR) gives you the right to access information held about you. Your right of access can be exercised in accordance with the Act. Any access request will be free of charge. You also have the right to: </p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Right of access by the data subject</p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Rectification and erasure</p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Right to rectification</p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Right to erasure ('right to be forgotten')</p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Right to restriction of processing</p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Notification obligation regarding rectification or erasure of personal data or restriction of processing</p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Right to data portability</p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Right to object and automated individual decision-making</p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Right to object</p>
							<p className='text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mb-6'>Automated individual decision-making, including profiling</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>1.8 Changes to our privacy policy (a) Any changes we may make to our privacy policy in the future will be posted on this page and, where appropriate, notified to you by email. Please check back frequently to see any updates or changes to our privacy policy.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>IN GENERAL</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>These privacy and security policies demonstrate The White Stripes’ firm commitment to your privacy and the protection of your information and to providing a safe, secure site for electronic commerce transactions. The White Stripes is committed to ensuring that your privacy is protected. Should we ask you to provide information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement. The White Stripes may change this policy by updating this page, so we suggest that you check this page from time to time to ensure that you are happy with any changes. The intellectual property rights in this website are owned and controlled by The White Stripes. All material featured and information provided on the website, whether text or images, are protected by copyright, trademark and other intellectual property rights and are owned by or licensed to The White Stripes. You may download, electronically copy or print any of the contents on condition that you are using them for personal and not for commercial purposes. Use for any other purpose is strictly prohibited without prior written permission from The White Stripes. No right, title or interest in any of the contents of this website will be transferred to you as a result of downloading, electronically copying or printing or attaching to email such material.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>SECURITY OF EMAIL CORRESPONDENCE</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>The website also invites you to contact The White Stripes via email, through the ‘appointment’ page. Email correspondence is free format text and cannot be encrypted, therefore it is not a secure means of communication. Please do not send sensitive information, such as passwords or credit card information, via email.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>INTERNET SECURITY</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>We take security very seriously and use the latest SSL (Secure Sockets Layer) encryption technology, this makes it extremely difficult for anyone else to decode. However, although we use advanced security measures to protect your information against loss, misuse and alteration, as is the case with all computer networks linked to the internet, we cannot absolutely guarantee the security of your information provided over the internet and will not be responsible for this.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>SECURITY POLICY</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>On placing an order through this website your personal details are protected from interception assuring your security. Depending on your browser, you will see a different confirmation that your connection is secure. In most cases, you will see a closed padlock at the foot of the browser. All transactions are confirmed and authorised by your card issuing bank. The White Stripes is rigorous in our approach in protecting the cardholder and we may contact you for additional security purposes should we deem this necessary.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>HOW WE USE COOKIES</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>A cookie is a small file which asks permission to be placed on your computer's hard drive. Once you agree, the file is added and the cookie helps analyse web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences. We use traffic log cookies to identify which pages are being used. This helps us analyse data about web page traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system. Overall, cookies help us provide you with a better website, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us. You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>LINKS TO OTHER SITES</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Our business associates and others, whose sites you may visit after clicking on a link from our site, may have less stringent policies on privacy. It is important to remember that The White Stripes does not have control over these policies and we urge you to read their privacy statements where available before providing any personally identifiable information. Some of our business associates, whose sites you may visit after clicking on a link from our site, use cookies. We do not have control over these cookies.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>HOW DO WE KEEP YOUR INFORMATION UP TO DATE?</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>We endeavour to keep all information we hold as accurate and up-to-date as possible. Please write to, The White Stripes, Cluster D, JLT, Dubai, UAE or email us at delight@whitestripes-tailoring.com to notify us of any changes to the information you have previously given to us, or if you are aware of any inaccuracy in the information we hold about you.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>WHO AT The White Stripes CAN SEE YOUR INFORMATION?</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>Information submitted to us is available to The White Stripes employees managing and using this information, but otherwise is kept confidential from other members of our staff.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>DO WE SHARE YOUR INFORMATION WITH OTHERS?</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>We may need to pass your information on to others solely to enable us to provide you with the goods or services you have ordered or requested from us or otherwise in connection with our relationship with you. If you permit us to do so by indicating at the time you register your details with us we may also occasionally pass your details to other companies in the The White Stripes group, as well as business associates or other carefully selected organisations to enable you to receive details of offers and events that may be of interest to you.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>WHAT DO WE DO WITH YOUR INFORMATION?</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>The White Stripes use your information to enable us to provide you with the goods or services you have ordered from us or otherwise in connection with your relationship with us. We may also use the information you provide to us to improve the content and appearance of our website or catalogues. With a view to understanding our customers better, and where you have indicated that you would like us to, we will retain the information about yourself you provide us with and details of any purchases you have made to enable us to offer products and services that are likely to interest you.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>HOW CAN YOU STOP RECEIVING MARKETING COMMUNICATIONS FROM US?</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>If you wish to cease receiving marketing or market research communications from us or would like us to cease processing your information in any other way you can simply unsubscribe using the link in any of the marketing emails we send, email us directly at delight@whitestripes-tailoring.com or write to us at The White Stripes, Cluster D, JLT, Dubai, UAE</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>TELEPHONE CALLS WITH US</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>As is the case with most other organisations, communications with The White Stripes by telephone may be recorded for the purposes of monitoring our customer service standards and for security.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>LEGAL MATTERS</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>If required by law The White Stripes will disclose personally identifiable information without your permission to the relevant legal authorities. This disclosure will be made in good faith belief that such disclosure is required to investigate or protect against suspected criminal activities to our customers, affiliates, visitors or property (including this website), or to others.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>DATA PROTECTION LEGISLATION</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>The White Stripes' will comply with UAE Government authorities in respect of any information we hold.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>NOTIFICATION OF CHANGES</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>In the event that The White Stripes change any of our Privacy and Security policies we will post details of the changes on this website. This will allow users to always be aware of our current policies. In the event that we decide to change our use of personally identifiable information in a way that is different from that stated at the time of collection of said information, then we will notify users by way of an email. We will give users a choice as to whether or not we use their information in the different manner.</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300 mt-6 mb-1 font-bold'>SCOPE OF THE PRIVACY AND SECURITY STATEMENT</p>
							<p className='text-justify lg:text-justify tracking-wider w-full lg:w-11/12 text-sm lg:text-base Raleway text-gray-300'>This Privacy and Security Statement applies to The White Stripes' UAE www.whitestripes-tailors.com</p>
						</div>
					</div>
					<Footer appointment={false} vipexperience={false}/>
				</div>
			</div>
		</>
	)
}

export default TermsAndCondition